// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempManager.Models;

#nullable disable

namespace Ch11Ex1TempManager.Migrations
{
    [DbContext(typeof(TempManagerContext))]
    partial class TempManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TempManager.Models.Temp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double?>("High")
                        .HasColumnType("REAL");

                    b.Property<double?>("Low")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Temps");
                });
#pragma warning restore 612, 618
        }
    }
}
